### PR TITLE
Voteend cron fixes

### LINKED ISSUE #124: move voteEnd cronjob to vercel

### LINKED ISSUE #125: voteEnd did not catch BEETS price
check pricefeeds again and make them more robust

### LINKED ISSUE #126: voteEnd did not catch all token prices
sum of bribes was calculated as 15,544 instead of 21,531

### LINKED ISSUE #127: Add page to display cron logs
we have a log entry every time a cron job runs, but no way to read it (except of direct database lookup)

### PR DESCRIPTION
**Pull request by onkeljoe**
fix many issues with voteEnd cronjob
- add voteEnd to vercel cron
- add beethovenX backen pricefeed for BPTs current and historic price
- fix pricefeed errors (multiple missing await)
- add new fBEETS price call to voteEnd (diverted by round no)
- store any valid tokenprices found to lastprice (reduces future api calls)
- exclude voteEnd run on non-voting weekends
- add a page to display cron logs, add a button to admin menu

fixes #124 
fixes #125 
fixes #126 
fixes #127

### CODE REVIEW

**Review by RnZ3 — APPROVED** [review]

File: src/pages/cronLogs.tsx [hunk 1]
```diff
@@ -0,0 +1,73 @@
...
+    if (!session) Router.push("/admin");
+  });
+
+  const cronlogs = trpc.cronlogs.list.useQuery(undefined, { enabled: !!session }).data?.entries;
+
+  if (session && status === "authenticated") {
+    if (!cronlogs)
+      return (
+        <>
+          <AdminNav />
```
Comment (mobiusTripper-crypto) [inline src/pages/cronLogs.tsx:33]: This is fine for now. But I think we should just have a single Admin NextPage, then all the admin pages now become components on that page ... I think that's a better way ... Somehow we need to have only a single use of AdminNav ... I'll make an issue

**Review by mobiusTripper-crypto — APPROVED** [review]
This looks great! All the price getting code is like magic to me. Someday maybe i'll dig in there to the details.
